services:
  rss-telegram:
    image:  asterix94/rss-telegram:latest
    container_name: rss-telegram
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=8531696383:AAH2jPw3BkfJg5yqUz1xY2NvPHq-TEHHkFA
      - TELEGRAM_CHAT_ID=-1003681679717
      - INCLUDE_DESCRIPTION=true
      - DISABLE_NOTIFICATION=true
      - CHECK_INTERVAL=3600
      - FEEDS_FILE=/app/data/feeds.txt
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
